<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>7.3</LangVersion>
    <RootNamespace>GameArchiver</RootNamespace>
    <AssemblyName>GameArchiver</AssemblyName>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PlayniteSDK" Version="6.16.0" />
  </ItemGroup>
  <ItemGroup>
    <None Include="extension.yaml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
